name: publish to nuget
on: push
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.200

    - name: Build project
      run: dotnet build -c Release
    
    - name: Run Unit Tests
      run: dotnet test

    - name: Generate a NuGet package
      run: dotnet pack --no-build -c Release -o .

    - name: Push to GitHub Package Registry
      run: dotnet nuget push "*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json